---
title: "Proyecto 1 Modelizacion Espacio Temporal"
author: "Josseling Quiroz y Carlitos Zuñiga"
date: "05/16/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r results='hide', warning = FALSE, message=FALSE}
library(FME)         # package used for calibration and uncertainty estimations
library(tidyverse)   # package used for data manipulation
library(gridExtra)   # package used for graphics with ggplot2
library(corrplot)
library(gplots)
library(RColorBrewer)
library(factoextra)
library(ggplot2)
library(ggpubr)
library(ggsci)
library(scales)
library (lubridate)
library(patchwork)
library (nsga2R)
library (mco)
```

```{r results='hide', warning = FALSE, message=FALSE}
################################################################################
# read data

inp <- read.csv("inp.csv",na.strings="")    		    # read input into dataframe
names(inp) <- c("Date","P1","PET1","Q1","ETA1","SM1","P2","PET2","Q2","ETA2","SM2","P3","PET3","Q3","ETA3","SM3","P4","PET4","Q4","ETA4","SM4","P5","PET5","Q5","ETA5","SM5","MEI")			            # define column names for direct use in model code
attach(inp,warn.conflicts = F)	
head(inp)
dim(inp) 

```
```{r results='hide', warning = FALSE, message=FALSE}

sumstat <- summary(inp)            # summary statistics
write.csv(sumstat, file="sumstat.csv")  # write output file to disc

# P-Q boxplots for comparison
b0 <- ggboxplot(P1,color="black", xlab="P1", ylab="P1 (mm/month)", ylim=c(0,1000)) 
b00 <- ggboxplot(Q1,color="blue", xlab="Q1", ylab="Q1 (mm/month)", ylim=c(0,1000)) 
b1 <- ggboxplot(P2,color="black", xlab="P2", ylab="P2 (mm/month)", ylim=c(0,1000)) 
b11 <- ggboxplot(Q2,color="blue", xlab="Q2", ylab="Q2 (mm/month)", ylim=c(0,1000)) 

plot <- ggarrange(b0, b00,
                  b1, b11,
                  ncol = 2, nrow = 2,  align = "hv", 
                  widths=c(10,10,10), heights=c(5,5,5))

ggexport(plotlist = plot, filename = "Ts_boxplot_P1.png", res = 300)

```

```{r results='hide', warning = FALSE, message=FALSE}
### correlation analysis on full matrix
corinp <- cor (inp[,2:27], use = "pairwise.complete.obs", method="spearman")      # calculates correlation coefficients
write.csv (corinp, file="cor5cuencas.csv")    # output matrix

corrplot(corinp, method="pie")                # nice pie plot
```

```{r results='hide', warning = FALSE, message=FALSE}

### bivariate plots with histograms and coefficients###
panel.cor <- function(x, y, method="spearman", digits=3, cex.cor=1.2)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- cor(x, y, use = "pairwise.complete.obs", method=method)
  ra <- cor.test(x, y, method=method)$p.value
  txt <- round(r, digits)
  sig <- 1
  prefix <- ""
  if(ra <= 0.1) prefix <- "."
  if(ra <= 0.05) prefix <- "*"
  if(ra <= 0.01) prefix <- "**"
  if(ra <= 0.001) prefix <- "***"
  if(ra <= 0.001) sig <- 2
  color <- 2
  if(r > 0) color <- "black"
  #         color <- "gray10"
  if(r < 0) color <- "gray50"
  txt <- paste(txt, prefix, sep="\n")
  text(0.5, 0.5, txt, cex = cex.cor, font=sig, col=color)
}
```

```{r results='hide', warning = FALSE, message=FALSE}
## Put histograms on the diagonal
panel.hist <- function(x, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(usr[1:2], 0, 2) )
  h <- hist(x, plot = FALSE)
  breaks <- h$breaks; nB <- length(breaks)
  y <- h$counts; y <- y/max(y)
  rect(breaks[-nB], 0, breaks[-1], y, col="cyan", ...)
  #         rect(breaks[-nB], 0, breaks[-1], y, col="gray", ...)
}

op <- par(mfrow=c(1,1), pty="s")      ##### create correlation matrix with histograms and coefficients
pairs(inp[,2:26],
      lower.panel = panel.cor, upper.panel = panel.smooth,
      diag.panel = panel.hist)
par(op)  
```

```{r results='hide', warning = FALSE, message=FALSE}
########## Regression analysis ######################################
PQ1 <- ggscatter(inp, x = "P1", y = "Q1",xlim=c(0,1000), ylim=c(0,1000),
                 size = 4, add = "reg.line")+
  stat_cor(label.x=200, label.y = -20) +
  stat_regline_equation(label.x=200, label.y = 0)
p1 <- PQ1 + labs(x = "Rainfall P (mm/month)", y = " Streamflow (mm/month)")

PQ2 <- ggscatter(inp, x = "P2", y = "Q2",xlim=c(0,1000), ylim=c(0,1000),
                 size = 4, add = "reg.line")+
  stat_cor(label.x=200, label.y = -20) +
  stat_regline_equation(label.x=200, label.y = 0)
p2 <- PQ2 + labs(x = "Rainfall P (mm/month)", y = "Streamflow (mm/month)")

grid.arrange(p1, p2, ncol = 2, nrow=1)

```

###### Time series analysis #################################

```

